name: music-semantic-recommender
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pandas
  - numpy
  - scikit-learn
  - jupyter
  - streamlit
  - plotly
  - pytest
  - pip:
      - sentence-transformers
